// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0mDiBkRFGSBshbMzzRc_X_2G7i2cHsRQ',
    appId: '1:395683120524:web:10354d205d9c6aa4b802a9',
    messagingSenderId: '395683120524',
    projectId: 'cvdesign-d9f32',
    authDomain: 'cvdesign-d9f32.firebaseapp.com',
    storageBucket: 'cvdesign-d9f32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4QPKWIYx719lnYZvPjYg48rWZRhTTGco',
    appId: '1:395683120524:android:89e17a0aeb8170e3b802a9',
    messagingSenderId: '395683120524',
    projectId: 'cvdesign-d9f32',
    storageBucket: 'cvdesign-d9f32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgQ-2VIBKYpAdSqE299CmBMaox4DMla4o',
    appId: '1:395683120524:ios:0fb0434d99717d6ab802a9',
    messagingSenderId: '395683120524',
    projectId: 'cvdesign-d9f32',
    storageBucket: 'cvdesign-d9f32.appspot.com',
    iosClientId: '395683120524-0eagekjc7d8frl0rag0cjp2np3pa0msp.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskCv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgQ-2VIBKYpAdSqE299CmBMaox4DMla4o',
    appId: '1:395683120524:ios:0fb0434d99717d6ab802a9',
    messagingSenderId: '395683120524',
    projectId: 'cvdesign-d9f32',
    storageBucket: 'cvdesign-d9f32.appspot.com',
    iosClientId: '395683120524-0eagekjc7d8frl0rag0cjp2np3pa0msp.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskCv',
  );
}
